id: P1B498F3E
initial_creation_type: ocr
source_metadata:
  volumes:
    9cd644033cb841f5a7eb2ba6d788f3fd:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: ཁྲོ་བོའི་རྒྱལ་པོ་འཕགས་པ་མི་གཡོ་བ་ལ་བསྟོད་པ།
      total_pages: 1044
      volume_number: 38
